### ISSUE TITLE
Pipeline Uyumluluğunun Sağlanması

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#103]
Pipeline için XML dosyalarının çalışılırlığının sağlanması ve bu issue altında detayları paylaşılmalıdır. İlgili maven komutları da yorum olarak issue altına eklenmelidir.

https://leylagln.medium.com/how-we-can-run-testng-xml-file-on-terminal-with-maven-4e2d277a4093

**Comment by ibrahimdenizz** [comment]
@Nbhtozcn Jiraya taşındı
