### ISSUE TITLE
Kullanıcı - Atama Tamamlama Servisinin Test Edilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#56]
Kullanıcı tarafında, atama başlatıldıktan sonra ilgili atama noktasına yetiştiğinde, atamanın tamamlanması için kullanılan servisin test case'ler yazılarak test edilmesi gerekmektedir.

---

**BE Servisi**
[POST | {{API_URL}}/api/v1/assignment/complete](https://documenter.getpostman.com/view/26813504/2s93kz55Jz#b3f2f5fa-ed88-4cca-b2fc-131c69aa8c4c)

**Comment by agitrubard** [comment]
BE Issue linki;
https://github.com/afet-yonetim-sistemi/ays-be/issues/100

**Comment by Nbhtozcn** [comment]
This issue is closed by commit number #53
