### ISSUE TITLE
Kullanıcı - Atama Başlama Servisinin Test Edilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#57]
Kullanıcı tarafında, atama onaylandıktan sonra atamaya başlamak için kullanılan servisin test case'ler yazılarak test edilmesi gerekmektedir.

---

**BE Servisi**
[POST | {{API_URL}}/api/v1/assignment/start](https://documenter.getpostman.com/view/26813504/2s93kz55Jz#0df9257a-484d-4b5b-9073-768ee9eae434)

**Comment by agitrubard** [comment]
**BE issue linki;**
https://github.com/afet-yonetim-sistemi/ays-be/issues/98

**Comment by Nbhtozcn** [comment]
This issue is closed by commit number #53
