### ISSUE TITLE
Kullanıcı - Atama Özet Servisinin Test Edilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#79]
Mobil tarafta ilgili kullanıcının ekranı kapatması, uygulamayı kapatıp açması gibi durumlarda kullanıcıyı kaldığı yerden devam ettirebilmesi için bir servis testlerinin yazılması gerekmektedir. Atamayı kontrol edebilmesi için; atamaya ait ID bilgisi, statü bilgisi, konum bilgisi gibi bilgilere ulaşabiliyor olması gerekmektedir.

---

**BE Issue**
https://github.com/afet-yonetim-sistemi/ays-be/issues/225

---

**BE Servisi**
[GET | {{API_URL}}/api/v1/assignment/summary](https://documenter.getpostman.com/view/26813504/2s93kz55Jz#5fe001a5-5365-4ed6-aa61-a374cd26604a)

**Comment by Nbhtozcn** [comment]
Completed by #86

**Comment by agitrubard** [comment]
> Completed by #86

Selamlar @Nbhtozcn,
Pull request içerisinde `Development` kısmından issue seçimi yapılırsa doğrudan ilişkilendirilmiş olur ve mergeleyince issue otomatik kapanır. Sadece tek yapmak gereken `Labels` ve `Projects` kısmını manuel olarak güncellemek.

![image](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/assets/61833677/f20b5d65-6dcf-4ef0-b6a7-c14c2e2ef3af)
