### ISSUE TITLE
Kullanıcı - Atama Detay Servisinin Test Edilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#80]
Mobil tarafta ilgili kullanıcının atama detayına erişebilmesi için bir servis testleri yazılmalıdır.

---

**BE Issue**
https://github.com/afet-yonetim-sistemi/ays-be/issues/232

---

**BE Servisi**
[GET | {{API_URL}}/api/v1/assignment](https://documenter.getpostman.com/view/26813504/2s93kz55Jz#72c1ea9f-10f9-44d5-b245-11f1f4cf751a)

**Comment by Nbhtozcn** [comment]
Completed by #86

**Comment by agitrubard** [comment]
> Completed by #86

Selamlar @Nbhtozcn,
Pull request içerisinde `Development` kısmından issue seçimi yapılırsa doğrudan ilişkilendirilmiş olur ve mergeleyince issue otomatik kapanır. Sadece tek yapmak gereken `Labels` ve `Projects` kısmını manuel olarak güncellemek.

![image](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/assets/61833677/f20b5d65-6dcf-4ef0-b6a7-c14c2e2ef3af)
