### ISSUE TITLE
Kullanıcı - Kişisel Bilgilere Erişim Servisinin Test Edilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#81]
Mobil tarafta ilgili kullanıcının detayına erişebilmesi için bir servis yazılmalıdır.

---

**BE Issue**
https://github.com/afet-yonetim-sistemi/ays-be/issues/240

---

**BE Servisi**
[GET | {{API_URL}}/api/v1/user-self](https://documenter.getpostman.com/view/26813504/2s93kz55Jz#916a65f6-b5bd-4124-939b-2da59dad4b4a)

**Comment by Nbhtozcn** [comment]
Completed by #86

**Comment by agitrubard** [comment]
> Completed by #86

Selamlar @Nbhtozcn,
Pull request içerisinde `Development` kısmından issue seçimi yapılırsa doğrudan ilişkilendirilmiş olur ve mergeleyince issue otomatik kapanır. Sadece tek yapmak gereken `Labels` ve `Projects` kısmını manuel olarak güncellemek.

![image](https://github.com/afet-yonetim-sistemi/ays-be-api-automation/assets/61833677/f20b5d65-6dcf-4ef0-b6a7-c14c2e2ef3af)
