### ISSUE TITLE
Kurum - Kayıt Başvurusu Detay Servisinin Test Edilmesi

### ISSUE THREAD

**Issue by agitrubard** [afet-yonetim-sistemi/ays-be-api-automation#90]
Kurum Yöneticisi Kayıt Başvurusu Yönetimi için Kayıt Başvurusu Detay Servisi için servis testleri yazılmalıdır.

---

**BE Issue**
https://github.com/afet-yonetim-sistemi/ays-be/issues/238

---

**BE Servisi**
[GET | {{API_URL}}/api/v1/admin/registration-application/{id}](https://documenter.getpostman.com/view/26813504/2s93kz55Jz#d3bbc1f3-25a5-4313-b7bd-f401a4bcd5c7)

**Comment by ibrahimdenizz** [comment]
@Nbhtozcn Jiraya taşındı
