### ISSUE TITLE
Create Test Cases for Endpoint Handling Edge Cases in Location Input

### ISSUE THREAD

**Issue by Nbhtozcn** [afet-yonetim-sistemi/ays-be-api-automation#96]
Validate the behavior of the following endpoints when encountering diverse extreme or unconventional location inputs:

- /api/v1/assignment

- /api/v1/assignment/{id}

- /api/v1/user/location

- /api/v1/assignment/search

**Comment by ibrahimdenizz** [comment]
@Nbhtozcn issue jiraya taşındı.
